export const DICTIONARY_API_URL = process.env.REACT_APP_DICTIONARY_API_URL;

export const PHOTOS_API_BASE_URL = process.env.REACT_APP_PHOTOS_API_BASE_URL;

export const PHOTOS_API_KEY = process.env.REACT_APP_PHOTOS_API_KEY;

export const DEFAULT_SEARCH_WORD = process.env.REACT_APP_DEFAULT_SEARCH_WORD;
